### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/rules.mk#29]
## General

* [x] top-level command aggregators: `help`, `build`, `bumpdeps`, `fmt`, `generate`, `install`, `lint`, `release`, `test`, `tidy`, `unittest`
* [x] self-update with `make bumpdeps`
* [x] generate AUTHORS file with `make generate`
* [x] `_linguist-kept` and `_linguist-ignored` helpers
* [x] `print-%` helper
* [ ] support `embedmd`
* [ ] create a new `repoman` repo and rewrite `rules.mk` in go with an easy-to-use CLI?
* [ ] add `--dry-run`, `--verbose`
* [ ] bot that runs various `rules.mk` commands on repos and open PRs
## Go

* [x] `go.unittest`
* [x] `go.lint` (with `golangci-lint`)
* [x] `go.release` (with `goreleaser`)
* [x] `go.checkdoc` (with `go doc`)
* [x] `go.coverfunc`
* [x] `go.tidy`
* [x] `go.build`
* [x] `go.bumpdeps` (with `go mod`)
* [x] `go.fmt` (with `goimports`)
* [x] CI optimizations
* [ ] support `CompileDaemon`

## Node

* [x] `npm.publish`

## Docker

* [x] `docker.build`
